import type { InvitationDemoContent } from '@/components/invitation/InvitationDemo'

export const demoContent: Record<string, InvitationDemoContent> = {
  'conte-dore': {
    heading: 'Yasmine & Karim',
    kicker: 'Mariage  ·  ٱلْعُرْس',
    subheading: 'Une histoire ancienne, un conte qui s\'écrit enfin à deux.',
    dateLabel: '12 Septembre 2026',
    locationLabel: 'Palais Es Saraya — Tunis',
    message: 'Comme dans les récits que l\'on se raconte le soir, deux chemins se sont croisés pour n\'en former qu\'un. Yasmine et Karim seraient honorés de votre présence pour célébrer ensemble le premier chapitre de leur conte doré.',
    highlights: [
      { time: '17h00', title: 'Cérémonie & Henné', desc: 'Accueil des invités sous les arcades du palais, au son du oud.' },
      { time: '19h30', title: 'Cortège d\'arrivée', desc: 'Entrée des mariés escortés par les musiciens traditionnels.' },
      { time: '20h30', title: 'Dîner de gala', desc: 'Un menu raffiné servi dans les jardins illuminés à la bougie.' },
      { time: '23h00', title: 'Soirée & danse', desc: 'Orchestre live et piste de danse jusqu\'au bout de la nuit.' },
    ],
    closing: 'Avec vous, l\'histoire sera plus belle encore',
    rsvpLabel: 'Confirmez votre présence avant le 1er septembre — nous avons hâte de vous compter parmi nous.',
  },
  'sidi-bou-said': {
    heading: 'Amira & Seïf',
    kicker: 'Fiançailles  ·  خطوبة',
    subheading: 'Entre ciel et mer, sur les hauteurs bleues et blanches du village.',
    dateLabel: '4 Juillet 2026 — 18h00',
    locationLabel: 'Terrasse du Café des Délices — Sidi Bou Saïd',
    message: 'Au-dessus des toits chaulés et des bougainvilliers, face à la baie de Tunis, Amira et Seïf souhaitent partager avec vous l\'instant où leurs familles se rencontrent enfin — un moment simple, lumineux, parfumé au jasmin.',
    highlights: [
      { time: '18h00', title: 'Accueil & machmoum', desc: 'Un brin de jasmin offert à chaque invité, à l\'entrée de la terrasse.' },
      { time: '18h45', title: 'Cérémonie de la khotba', desc: 'L\'échange des alliances face au coucher de soleil sur la baie.' },
      { time: '20h00', title: 'Thé à la menthe & douceurs', desc: 'Pâtisseries tunisiennes et thé servi dans la pure tradition.' },
      { time: '21h30', title: 'Musique & lanternes', desc: 'Mélodies live inspirées du légendaire Café des Délices.' },
    ],
    closing: 'Venez peindre ce moment en bleu et blanc avec nous',
    rsvpLabel: 'Merci de confirmer votre venue avant le 20 juin — la terrasse vous attend, drapée de jasmin.',
  },
  'jardin-andalou': {
    heading: 'La Nuit du Henné de Rim',
    kicker: 'Henné  ·  ليلة الحناء',
    subheading: 'Une soirée de couleurs, de chants et de mains ornées.',
    dateLabel: '21 Août 2026 — 20h00',
    locationLabel: 'Jardins de Dar El Andalous — Hammamet',
    message: 'Sous les arcades fleuries et près des fontaines de mosaïque, la famille de Rim vous convie à célébrer la veille de ses noces. Une nuit de henné, de musique et de douceurs — où chaque main ornée raconte une bénédiction.',
    highlights: [
      { time: '20h00', title: 'Arrivée & cortège', desc: 'Procession aux chandelles dans les allées du jardin andalou.' },
      { time: '20h45', title: 'Cérémonie du henné', desc: 'Application traditionnelle au son des tambourins et youyous.' },
      { time: '21h30', title: 'Chants & troupe folklorique', desc: 'Musique live et danses populaires autour de la fontaine.' },
      { time: '23h00', title: 'Buffet de douceurs', desc: 'Pâtisseries orientales, thé à la menthe et fruits de saison.' },
    ],
    closing: 'Venez en blanc et vert, parfumés de fleurs d\'oranger',
    rsvpLabel: 'Confirmez votre présence avant le 10 août pour qu\'on vous garde une place près de la fontaine.',
  },
  'nuit-etoilee': {
    heading: 'Nour & Adam',
    kicker: 'Mariage  ·  Soirée de gala',
    subheading: 'Sous un ciel constellé, une nuit pour ne jamais oublier.',
    dateLabel: '3 Octobre 2026 — 21h00',
    locationLabel: 'Domaine El Manar — Gammarth',
    message: 'Quand deux étoiles se rencontrent, elles éclairent le ciel entier. Nour et Adam vous invitent à une soirée sous les lanternes et les constellations, pour célébrer leur union dans la douceur d\'une nuit dorée.',
    highlights: [
      { time: '21h00', title: 'Cocktail sous les étoiles', desc: 'Accueil en terrasse, lanternes suspendues et musique douce.' },
      { time: '22h00', title: 'Entrée des mariés', desc: 'Une arrivée scénographiée sous une pluie d\'étincelles dorées.' },
      { time: '22h45', title: 'Dîner aux chandelles', desc: 'Un menu signature servi sous voûte étoilée.' },
      { time: '00h30', title: 'Bal & feu d\'artifice', desc: 'Première danse, orchestre live et clôture en lumière.' },
    ],
    closing: 'Brillez avec nous, le temps d\'une nuit infinie',
    rsvpLabel: 'Merci de répondre avant le 15 septembre — les étoiles n\'attendent que vous.',
  },
  'rose-poudree': {
    heading: 'Les 30 ans de Salma',
    kicker: 'Anniversaire  ·  عيد ميلاد',
    subheading: 'Une après-midi tout en douceur, en rose et en rires.',
    dateLabel: '14 Mai 2026 — 16h00',
    locationLabel: 'Maison d\'hôtes Dar Zarrouk — La Marsa',
    message: 'Pour célébrer trois décennies de sourires, de voyages et d\'amitiés précieuses, Salma vous ouvre les portes d\'un goûter délicat — entre fleurs séchées, thé glacé et musique douce. Une parenthèse tendre, à son image.',
    highlights: [
      { time: '16h00', title: 'Accueil & welcome drink', desc: 'Limonades florales et petits-fours sucrés-salés.' },
      { time: '17h00', title: 'Jeux & souvenirs', desc: 'Un moment ludique autour de l\'album de ses 30 ans.' },
      { time: '18h00', title: 'Goûter & gâteau', desc: 'Pâtisserie signature et chants d\'anniversaire.' },
      { time: '19h30', title: 'Photobooth & musique', desc: 'Coin photo fleuri et playlist douce pour finir en beauté.' },
    ],
    closing: 'Venez comme vous êtes, le rose vous va si bien',
    rsvpLabel: 'Merci de confirmer avant le 5 mai pour que la table soit aussi jolie que vous.',
  },
  'corporate-silver': {
    heading: 'Lancement — Atlas Capital',
    kicker: 'Événement d\'entreprise',
    subheading: 'Présentation officielle de notre nouvelle identité de marque.',
    dateLabel: '9 Juin 2026 — 09h30',
    locationLabel: 'The Tunis Business Center — Les Berges du Lac',
    message: 'Atlas Capital a le plaisir de vous convier au lancement officiel de sa nouvelle plateforme d\'investissement. Une matinée de présentations, d\'échanges et de perspectives, en présence de nos partenaires et de notre comité exécutif.',
    highlights: [
      { time: '09h30', title: 'Accueil & networking', desc: 'Café de bienvenue et rencontre avec les équipes dirigeantes.' },
      { time: '10h00', title: 'Keynote d\'ouverture', desc: 'Présentation de la vision et de la nouvelle identité de marque.' },
      { time: '11h00', title: 'Table ronde', desc: 'Échanges avec nos partenaires sur les perspectives du marché.' },
      { time: '12h30', title: 'Cocktail déjeunatoire', desc: 'Networking informel autour d\'un buffet signature.' },
    ],
    closing: 'Construisons l\'avenir, ensemble',
    rsvpLabel: 'Merci de confirmer votre présence avant le 1er juin via le formulaire dédié aux partenaires.',
  },
  'toge-et-sceau': {
    heading: 'Soutenance de Mehdi Trabelsi',
    kicker: 'Soutenance de thèse de doctorat',
    subheading: '« Approches algorithmiques pour l\'optimisation des réseaux intelligents »',
    dateLabel: '26 Juin 2026 — 14h00',
    locationLabel: 'Amphithéâtre d\'Honneur — Université de Tunis El Manar',
    message: 'C\'est avec une profonde émotion que Mehdi Trabelsi vous convie à la soutenance publique de sa thèse de doctorat, devant un jury d\'éminents professeurs. Votre présence honorerait l\'aboutissement de longues années de recherche et de persévérance.',
    highlights: [
      { time: '14h00', title: 'Ouverture de la séance', desc: 'Accueil du jury, du candidat et de l\'assistance par le président de séance.' },
      { time: '14h15', title: 'Présentation des travaux', desc: 'Exposé des résultats de recherche par le candidat (45 minutes).' },
      { time: '15h15', title: 'Questions du jury', desc: 'Échanges et délibération entre le candidat et les membres du jury.' },
      { time: '17h00', title: 'Proclamation & vin d\'honneur', desc: 'Annonce des résultats suivie d\'un moment convivial de partage.' },
    ],
    closing: 'Un parcours s\'achève, une carrière commence',
    rsvpLabel: 'Merci de confirmer votre présence avant le 20 juin auprès du secrétariat de la faculté.',
  },
  'petits-nuages': {
    heading: 'Bienvenue, petit trésor',
    kicker: 'Gender Reveal  ·  Famille Selmi',
    subheading: 'Garçon ou fille ? Venez le découvrir avec nous, en confettis et en rires !',
    dateLabel: '2 Août 2026 — 15h00',
    locationLabel: 'Jardin de la famille Selmi — Sousse',
    message: 'Un petit cœur grandit, et bientôt nous saurons s\'il bat en rose ou en bleu ! La famille Selmi vous invite à un après-midi tendre et joyeux, pour ouvrir ensemble la grande boîte à confettis et célébrer l\'arrivée prochaine de bébé.',
    highlights: [
      { time: '15h00', title: 'Accueil & limonades', desc: 'Bulles, ballons pastel et coin photo « Team Rose / Team Bleu ».' },
      { time: '15h45', title: 'Jeux & devinettes', desc: 'Pronostics en famille : qui devinera la couleur surprise ?' },
      { time: '16h30', title: 'Le grand moment', desc: 'Ouverture du ballon géant — révélation en pluie de confettis !' },
      { time: '17h00', title: 'Goûter & gâteau', desc: 'Pâtisseries douces et photos souvenirs pour clore la journée.' },
    ],
    closing: 'Venez habillés de rose ou de bleu — à vous de choisir votre camp !',
    rsvpLabel: 'Merci de confirmer votre présence avant le 25 juillet — la surprise n\'attend que vous.',
  },
}
